### ISSUE TITLE
Add OAUTH_ACCESS_TOKEN & OAUTH_REFRESH_TOKEN to organization secrets

### ISSUE THREAD

**Issue by calvintam236** [TinyCommunity/tinylist2#10]
Hey @WieFel,

Can you add those tokens in organization secrets to be shared across repos? Then, we don’t need to have per repo secrets.

https://github.com/organizations/TinyCommunity/settings/secrets/actions

**Comment by WieFel** [comment]
sorry, will do ASAP.
so you mean put the same `OAUTH_ACCESS_TOKEN` + `OAUTH_REFRESH_TOKEN` as organization secrets as we have in tinycolor2 repo?

**Comment by calvintam236** [comment]
> sorry, will do ASAP.
> so you mean put the same `OAUTH_ACCESS_TOKEN` + `OAUTH_REFRESH_TOKEN` as organization secrets as we have in tinycolor2 repo?

Yep

**Comment by WieFel** [comment]
@calvintam236 done
